const mongoose = require("../connect");
var mon = require('mongoose');
var Schema = mon.Schema;
var propiedadSchema = new Schema ({
  estado: String,
  descripcion: String,
  fecha_entrega: { type: Date, default: Date.now },
  supterreno: String,
  amurallado: Boolean,
  servicios_basicos: String,
  anio_construccion: Date,
  deshabitacion: String,
  descripcion_banio: String,
  numero_banios: Number,
  numero_habitaciones: Number,
  supconstruida: Number,
  supterraza: Number,
  pisos: Number,
  elevador: Boolean,
  baulera: Boolean,
  piscina: Boolean,
  garaje: Boolean,
  numparqueos: Number,
  amoblado: Boolean,
  fecha_publicacion: Date,
  ubicacion: String,
  direccion: String,
  rating: Number,
  precio: String,
  moneda: String,
  tipo_oferta: String,
  tipo_vivienda: String,
  nombre_zona: String,
  nombre_ciudad: String,
  latitud: String,
  longitud: String,
  gallery: Array,
  nombre_dueno: String,
  apellido_dueno: String,
  telefono_dueno: Number,
  telefono_ref_dueno: Number,
  celular_dueno: Number,
  email_dueno: String,
  ciudad_dueno: String
});
var propiedad= mongoose.model("propiedad",propiedadSchema );
module.exports = propiedad;
